
// Valid request
POST {{BaseAddress}}/shops
Content-Type: application/json

{
    "name": "shop name",
    "description": "shop description",
    "city":"city",
    "street":"street",
    "groupIds":[
      "dc54bec6-e5b2-4d6b-90fd-9c5fdfcb6cdc"
    ]
}

###
// Invalid Request
POST {{BaseAddress}}/shops
Content-Type: application/json

{
    "name": "shop name",
    "description": "shop description",
    "city":" ",
    "street":""
}
