

services:
  catalog-db:
    container_name: catalog_mssql_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 14330:1433
    environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: Passw0r!d
       MSSQL_PID: Developer
    volumes:
      - catalog-db-volume:/var/opt/mssql/ 

  RabbitMq:
    container_name: rabbit
    image: rabbitmq:4.0.4-management-alpine
    ports:
      - 15672:15672
      - 5672:5672


volumes:
  catalog-db-volume: