# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname = localhost
@port = 7177
@base = https://{{hostname}}:{{port}}/api

@productId = 00000000-0000-0000-0000-000000000000

GET {{base}}/product-groups

###

GET {{base}}/product-groups/{{productId}}

###
GET {{base}}/product-groups/c133e017-d8a9-4303-a4d6-3c5f56349418
