
//Valid request

POST {{BaseAddress}}/groups
Content-Type : application/json

{
    "name": "group name",
    "description": "group description"
}

###

//Invalid request
Post {{BaseAddress}}/groups
Content-Type : application/json
{
    "name": "",
    "description": " "
}