@hostname = localhost
@port = 7177
@base = https://{{hostname}}:{{port}}/api


@productId = 8c72dc4a-9c3d-4ca8-acfb-897dc700aafa
@productGroupId = 4b237115-9de7-4bd0-a933-e9403cd289d8



POST {{base}}/products/{{productId}}/remove-group
Content-Type: application/json

{
  "productGroupId":"{{productGroupId}}"
}