@hostname = localhost
@port = 7177
@base = https://{{hostname}}:{{port}}/api

POST {{base}}/products
Content-Type: application/json

{
  "productName": "Product Name-2",
  "productCode": "ProductCode-2",
  "productDefinition": "Product definition-2"
}

###

POST {{base}}/products
Content-Type: application/json

{
  "productName": "",
  "productCode": "",
  "productDefinition": ""
}