@hostname = localhost
@port = 7177
@base = https://{{hostname}}:{{port}}/api


@productId = 74169806-88b5-4765-b236-4b15054c9b0a
@productGroupId = 556decad-f3c1-4cba-ab45-48dc45fa3b22


POST {{base}}/products/{{productId}}/add-group
Content-Type: application/json

{
  "productGroupId":"{{productGroupId}}"
}