@hostname = localhost
@port = 7177
@base = https://{{hostname}}:{{port}}/api


@productId = 73ea84b7-60ef-4e7d-98be-09daaa18a7a5
@productGroupId = 6651d453-d2dd-4f44-95fb-d798b69a5367


POST {{base}}/products/{{productId}}/remove-group
Content-Type: application/json

{
  "productGroupId":"{{productGroupId}}"
}