# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname = localhost
@port = 7177
@base = https://{{hostname}}:{{port}}/api

DELETE {{base}}/products/{{$guid}}

###

DELETE {{base}}/products/a1166e6b-82b9-4487-a52e-b54c1933aea6